version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: metro-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Sup3rsecret
      MYSQL_DATABASE: metro
    ports:
      - "3312:3306"
    volumes:
      - metro-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: metro-phpmyadmin
    restart: always
    ports:
      - "8084:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: Sup3rsecret


  app:
    build:
      context: .
    container_name: metro-app
    ports:
      - "8282:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: root
      DB_PASS: Sup3rsecret
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: metro

volumes:
  metro-db:
